"use client";

import Link from "next/link";
import { Network } from "lucide-react";
import { usePathname } from "next/navigation";

export function Footer() {
    const pathname = usePathname();
    if (pathname.startsWith("/app")) return null;

    return (
        <footer className="border-t bg-muted/40">
            <div className="container mx-auto px-4 py-8 md:py-12">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                    <div className="md:col-span-1 space-y-4">
                        <Link href="/" className="flex items-center space-x-2 font-bold text-xl text-primary">
                            <Network className="h-6 w-6" />
                            <span>Eventis</span>
                        </Link>
                        <p className="text-sm text-muted-foreground">
                            Court-ready medical chronologies, generated by ontology-driven AI.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h4 className="text-sm font-semibold tracking-wide uppercase text-foreground">Product</h4>
                        <ul className="space-y-2 text-sm text-muted-foreground">
                            <li><Link href="/product" className="hover:text-primary">Workflow</Link></li>
                            <li><Link href="/sample" className="hover:text-primary">Sample Outputs</Link></li>
                            <li><Link href="/pricing" className="hover:text-primary">Pricing</Link></li>
                            <li><Link href="/pilot" className="hover:text-primary">Request Pilot</Link></li>
                        </ul>
                    </div>

                    <div className="space-y-4">
                        <h4 className="text-sm font-semibold tracking-wide uppercase text-foreground">Technology</h4>
                        <ul className="space-y-2 text-sm text-muted-foreground">
                            <li><Link href="/tech" className="hover:text-primary">Ontology Engine</Link></li>
                            <li><Link href="/security" className="hover:text-primary">Security</Link></li>
                            <li><Link href="/tech#audit" className="hover:text-primary">Audit Trail</Link></li>
                        </ul>
                    </div>

                    <div className="space-y-4">
                        <h4 className="text-sm font-semibold tracking-wide uppercase text-foreground">Company</h4>
                        <ul className="space-y-2 text-sm text-muted-foreground">
                            <li><Link href="#" className="hover:text-primary">About</Link></li>
                            <li><Link href="#" className="hover:text-primary">Contact</Link></li>
                            <li><Link href="#" className="hover:text-primary">Privacy Policy</Link></li>
                            <li><Link href="#" className="hover:text-primary">Terms of Service</Link></li>
                        </ul>
                    </div>
                </div>

                <div className="mt-8 pt-8 border-t text-center text-sm text-muted-foreground">
                    <p>&copy; {new Date().getFullYear()} Eventis. All rights reserved.</p>
                </div>
            </div>
        </footer>
    );
}
