export const terms = {
  marketing: {
    productName: "LineCite",
    tagline: "Deterministic Medical Intelligence for Litigation",
    description: "Citation-anchored, export-validated medical chronologies built specifically for plaintiff-side litigation.",
  },
  app: {
    navigation: {
      dashboard: "Dashboard",
      allMatters: "All Matters",
      newMatter: "New Matter",
      chronologies: "Chronologies",
      expertReports: "Expert Reports",
      settings: "Settings",
      signOut: "Sign Out",
    },
    metrics: {
      totalMatters: "Total Matters",
      newThisWeek: "New This Week",
      exposureScore: "Exposure Score",
      systemStatus: "System Status",
      riskGapsFound: "Risk Gaps Found",
      citationsVerified: "Citations Verified",
      defenseExposure: "Defense Exposure",
      systemUptime: "System Uptime",
    },
    status: {
      verified: "Verified",
      review: "Review Recommended",
      blocked: "Blocked",
      pending: "Pending",
      processing: "Processing",
      ready: "Ready",
      failed: "Failed",
    },
    risk: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    actions: {
      initializeMatter: "Initialize Matter",
      createNewMatter: "Create New Matter",
      browseRegistry: "Browse Matter Registry",
      export: "Export",
      upload: "Upload",
      runExtraction: "Run Extraction",
      validateAudit: "Validate in Audit Mode",
      exportChronology: "Export chronology and specials",
    },
    labels: {
      matterMatrix: "Matter Matrix",
      sortBy: "Sort",
      highestExposureFirst: "Highest Exposure First",
      highestCciFirst: "Highest CCI First",
      recentlyAnalyzed: "Recently Analyzed",
      matterName: "Matter Name (A-Z)",
      exposureIndex: "Exposure Index",
      cciIndex: "CCI Index",
      pages: "Pages",
      integrity: "Integrity",
      lastAnalyzed: "Last Analyzed",
      created: "Created",
    },
  },
  export: {
    validationSummary: "Export Validation Summary",
    chronology: "Chronology",
    specialsSummary: "Specials Summary",
    missingRecords: "Missing Records",
    pdfExport: "PDF Export",
  },
  review: {
    auditMode: "Audit Mode",
    caseDetails: "Case Details",
    chronology: "Chronology",
    timeline: "Timeline",
    findings: "Key Findings",
    billing: "Billing & Specials",
    causation: "Causation Chain",
    conflicts: "Evidentiary Conflicts",
    structuralRisks: "Structural Risks",
    sourceCitation: "Source Citation",
  },
  errors: {
    noRunsFound: "No runs found in artifact",
    noArtifact: "No evidence_graph.json found",
    unauthorized: "Unauthorized",
    notFound: "Not Found",
  },
} as const;

export type Terms = typeof terms;
export type AppStatus = keyof typeof terms.app.status;
export type AppRisk = keyof typeof terms.app.risk;
